language: c
sudo: required
services:
 - docker
script:
 - make OPTIMIZ="-O3 -s"
 - make tar BUILD_NUM=$TRAVIS_BUILD_NUMBER
 - make tlkit.spec BUILD_NUM=$TRAVIS_BUILD_NUMBER
 - docker-rpm-builder dir alanfranz/drb-epel-7-x86-64:latest . .
 - rm -f */*-debuginfo-*.rpm
 - ./relmgr
 - package_cloud push aliuly/localapps/el/7 */*.el7.*.rpm
before_install:
 - sudo apt-get update
 - sudo -H pip install docker-rpm-builder
 - gem install package_cloud
compiler: gcc
env:
  global:
   - secure: "JiXJhPkUsFPJkLxCqQwN1KjuMfJE26KglOyz+cE8ZMrZWPoLKNPk4qIe6bxj029SLoFdYzl0O9ulTppTV5QlnnYoEp6P44IFkEcTT2WGfczSyjdumiqUu0eU5v6hCpcwClwI+Cxfuy3BUldR6Pn5zPwzb1JLXY7l7RMqwdLTNtxM1D6Q7La7rInM3l7txIboD99ooQixufI1CqhR6BfJLBxSCVDcFSCKGp3qOhHqeKE/6+PJ0rajZzFoGvWH9CMEugpV52AMD+dT+YZ3xfgD6aU8zVZWhaZGdjDVEMyBx0NuWVU0nxd1u2D7aBScKWew3Lyb7wESZzD8QjPed6dLheiFFQGPlejjOonnZ7GEwFBKMHfFFH5q35wgQLBaWTae+aueJpxnoPJI8wpuIqdPBDQQAXYxmH+nyht5mCJJ1/XGVJQR9UyDHwPY3sAOBK578PGbubEt7MOofToCe/zoNx+XqGLcW9JEggxZXqmHRq5DNKZB/2PHSVxfQ+bYPaj+KxukaQTb9V1aSwzTcEn8j+er5ezNWRB+XL4xmRkWfluvKKlZhE4EpEqvhoNPuRLoMPBHkZJFgNQIaNvhBO86Eq8biEzZQInn39hAjuzFXCaINqoOC86zahTckPFWLOlPVpDkBeCqm3IEU4lB1NXmzMk33M4rCO+fAgWWNZ6uN1o="
   - secure: "KR/TdOXnH/aJG95zDzXAD4euNSCdWoQ5AIt0/mzwRz1bWJFKHxhBKL0cVDJ+y8afB67NeS3EFyRDVhReHICG0pHK5kiQmOEnuHcb12LfynDECSBiT8p0eiXNh0nDqKlvaNjFo/0JLTQ+Xw7oySGhKphBd4rreFsgNGOXj8Q4ciK9yzfQuAAevqLFdEcC20P5PYGjau//3nDSxm36ox71m8NyGjW8fWppLbntFkjfp3Xsa7xk8AHkTSm5ivT1IJifwm0E+hgDgS95NE+pGje+gYOKidz5z9bsbTFF+FE+kZUS9Pm1aRsffS4AKlF6hGQzLj1I6DweaSlI9N0t1itSXvzxQqU3UvBrlG4QcsWQhgW32RMlyWG3LjPQzoL4rbVb8Adj1cd7q0vsWqd3rLOnoxNnzSEUda7bxQA0OTfcIaqPTn3vgoO2gHAB4v3hvjmLaHJ3VVR44cpOE52fWqnCGayjriC7zaiR+A1IxdmInpztaUU84Bor/CX/BY6uKvFFf5/y+k049YW6a0SKKZe9eh5ztYb3CqVwn2raytutGW2uATuR8xL3b4+JdP7+vtWwznPpHf3OS9C+5tl6cIY/0UF32/rSHuPzVHRufucletiVxiCw4YqcmxQx4/m8fFez5Co7N45moYTUWJ+bs/jdYqlsN0E2tIuPPz7VR4XeWUQ="

