#
language: c
sudo: required
services:
 - docker
script:
 - make OPTIMIZ="-O3 -s"
 - make tar BUILD_NUM=$TRAVIS_BUILD_NUMBER
 - make tlkit.spec BUILD_NUM=$TRAVIS_BUILD_NUMBER
 - docker-rpm-builder dir alanfranz/drb-epel-7-x86-64:latest . .
 - ls -l
before_install:
 - sudo apt-get update
 - sudo -H pip install docker-rpm-builder
 - # sudo apt-get -y install docker-rpm-builder
compiler: gcc
